#https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

#kubectl -f apply k8s/nginx/deployment.yaml
#kubectl get deployment
#kubectl get deployment nginx-deployment
#kubectl get pods
#kubectl exec -it <podname> -- /bin/bash    => to execute a running container in pod  
#kubectl delete -f k8s/nginx/deployment.yaml  => to exit deployment config

apiVersion : apps/v1
kind : Deployment
metadata :
  name : nginx-deployment
spec :
  replicas : 3 # to create multiple pods
  selector :
    matchLabels:
      app : nginx-deployment
  template :
    metadata : 
      labels : 
        app : nginx-deployment
    spec : 
      containers :
        - name : nginx
          image : nginx-latest #to fetch image from docker hub
          ports :
            - containerPort : 80