#kubectl -f apply k8s/nginx/deployment.yaml
#kubectl get deployments
#kubectl get deployment nginx-deployment
#kubectl -f apply k8s/nginx/service.yaml
#kubectl get service
#kubectl get service nginx-service -o yaml

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx-deployment