#kubectl -f apply k8s/apps/iac-python-fastapi.yaml
#kubectl get deployment
#kubectl get pods
#kubectl exec -it <podname> -- /bin/bash    => to execute a running container in pod  

apiVersion : apps/v1
kind : Deployment
metadata :
  name : iac-python-deployment
spec :
  replicas : 3 # to create multiple pods
  selector :
    matchLabels:
      app : iac-python-deployment
  template :
    metadata : 
      labels : 
        app : iac-python-deployment
    spec : 
      containers :
        - name : iac-python
          image : codingforentrepreneurs/iac-python:latest #to fetch image from docker hub
          env :
            - name : PORT
              value : "8181"
          ports :
            - containerPort : 8181

---

apiVersion: v1
kind: Service
metadata:
  name: iac-python-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
  selector:
    app: iac-python-deployment