name: Build Docker Container and Push to Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches : [master]
  pull_request:
    branches : [master]

jobs:
  test_django_job:
    uses: OmkarPawaskar/Deploy-Django-into-Production-with-Kubernetes-Docker-Github-Actions/.github/workflows/test-django.yaml@master
  docker_build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      DJANGO_SECRET_KEY: test-key-not-good-maybe-make-one-better
    steps:
    - uses: actions/checkout@v2
    